export const PERMISSIONS = {
  PRODUCTS_VIEW: 'products.view',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_UPDATE: 'products.update',
  PRODUCTS_DELETE: 'products.delete',
  INVOICES_VIEW: 'invoices.view',
  INVOICES_CREATE: 'invoices.create',
  INVOICES_RETURN: 'invoices.return',
  DISCOUNTS_PRODUCT: 'discounts.product',
  DISCOUNTS_INVOICE: 'discounts.invoice',
  PRICE_OVERRIDE: 'price.override',
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',
  PRINTING_RECEIPT: 'printing.receipt',
  PRINTING_BARCODE: 'printing.barcode',
  LICENSE_VIEW: 'license.view',
  LICENSE_MANAGE: 'license.manage',
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_UPDATE: 'settings.update',
  USERS_MANAGE: 'users.manage',
  ROLES_MANAGE: 'roles.manage',
  CATEGORIES_VIEW: 'categories.view',
  CATEGORIES_CREATE: 'categories.create',
  CATEGORIES_UPDATE: 'categories.update',
  BRANDS_VIEW: 'brands.view',
  BRANDS_CREATE: 'brands.create',
  BRANDS_UPDATE: 'brands.update',
  BRANDS_DELETE: 'brands.delete',
  UNITS_VIEW: 'units.view',
  UNITS_CREATE: 'units.create',
  UNITS_UPDATE: 'units.update',
  UNITS_DELETE: 'units.delete',
  SUPPLIERS_VIEW: 'suppliers.view',
  SUPPLIERS_CREATE: 'suppliers.create',
  SUPPLIERS_UPDATE: 'suppliers.update',
  CLIENTS_VIEW: 'clients.view',
  CLIENTS_CREATE: 'clients.create',
  CLIENTS_UPDATE: 'clients.update',
  EMPLOYEES_VIEW: 'employees.view',
  EMPLOYEES_MANAGE: 'employees.manage',
  PURCHASES_VIEW: 'purchases.view',
  PURCHASES_CREATE: 'purchases.create',
  PURCHASES_UPDATE: 'purchases.update',
  PURCHASES_RETURN: 'purchases.return',
  PAYMENTS_VIEW: 'payments.view',
  PAYMENTS_CREATE: 'payments.create',
  SHIFTS_VIEW: 'shifts.view',
  SHIFTS_OPEN: 'shifts.open',
  SHIFTS_CLOSE: 'shifts.close',
  SHIFTS_DRAWER_MANAGE: 'shifts.drawer.manage',
  AUDIT_VIEW: 'audit.view',
  ALERTS_VIEW: 'alerts.view',
  ALERTS_ACKNOWLEDGE: 'alerts.acknowledge',
  INVENTORY_ADJUSTMENTS_VIEW: 'inventory.adjustments.view',
  INVENTORY_ADJUSTMENTS_CREATE: 'inventory.adjustments.create',
  EXPENSES_VIEW: 'expenses.view',
  EXPENSES_CREATE: 'expenses.create',
  EXPENSES_CATEGORIES: 'expenses.categories',
} as const

export const FEATURES = {
  MULTIPLE_UNITS: 'multiple_units',
  MULTIPLE_BARCODES: 'multiple_barcodes',
  WHOLESALE_PRICE: 'wholesale_price',
  PRODUCT_DISCOUNT: 'product_discount',
  INVOICE_DISCOUNT: 'invoice_discount',
  PRICE_OVERRIDE: 'price_override',
  LOW_STOCK_REPORT: 'low_stock_report',
  RECEIPT_PRINTING: 'receipt_printing',
  BARCODE_PRINTING: 'barcode_printing',
  CATEGORIES: 'categories',
  BRANDS: 'brands',
} as const

export const PERMISSION_LABELS: Record<string, string> = {
  'products.view': 'عرض المنتجات',
  'products.create': 'إنشاء المنتجات',
  'products.update': 'تعديل المنتجات',
  'products.delete': 'حذف المنتجات',
  'invoices.view': 'عرض الفواتير',
  'invoices.create': 'إنشاء الفواتير',
  'invoices.return': 'مرتجعات البيع',
  'discounts.product': 'خصم الصنف',
  'discounts.invoice': 'خصم الفاتورة',
  'price.override': 'تعديل السعر',
  'reports.view': 'عرض التقارير',
  'reports.export': 'تصدير التقارير',
  'printing.receipt': 'طباعة الإيصالات',
  'printing.barcode': 'طباعة الباركود',
  'license.view': 'عرض الترخيص',
  'license.manage': 'إدارة الترخيص',
  'settings.view': 'عرض الإعدادات',
  'settings.update': 'تعديل الإعدادات',
  'users.manage': 'إدارة المستخدمين',
  'roles.manage': 'إدارة الأدوار',
  'categories.view': 'عرض الفئات',
  'categories.create': 'إنشاء الفئات',
  'categories.update': 'تعديل الفئات',
  'brands.view': 'عرض الماركات',
  'brands.create': 'إنشاء الماركات',
  'brands.update': 'تعديل الماركات',
  'brands.delete': 'حذف الماركات',
  'units.view': 'عرض الوحدات',
  'units.create': 'إنشاء الوحدات',
  'units.update': 'تعديل الوحدات',
  'units.delete': 'حذف الوحدات',
  'suppliers.view': 'عرض الموردين',
  'suppliers.create': 'إنشاء الموردين',
  'suppliers.update': 'تعديل الموردين',
  'clients.view': 'عرض العملاء',
  'clients.create': 'إنشاء العملاء',
  'clients.update': 'تعديل العملاء',
  'employees.view': 'عرض الموظفين',
  'employees.manage': 'إدارة الموظفين',
  'purchases.view': 'عرض المشتريات',
  'purchases.create': 'إنشاء المشتريات',
  'purchases.update': 'تعديل وترحيل المشتريات',
  'payments.view': 'عرض الدفعات',
  'payments.create': 'تسجيل الدفعات',
  'shifts.view': 'عرض الورديات',
  'shifts.open': 'فتح الورديات',
  'shifts.close': 'إغلاق الورديات',
  'expenses.view': 'عرض المصروفات',
  'expenses.create': 'تسجيل المصروفات',
  'expenses.categories': 'إدارة تصنيفات المصروفات',
}

export const RESOURCE_LABELS: Record<string, string> = {
  products: 'المنتجات',
  invoices: 'الفواتير',
  discounts: 'الخصومات',
  price: 'الأسعار',
  reports: 'التقارير',
  printing: 'الطباعة',
  license: 'الترخيص',
  settings: 'الإعدادات',
  users: 'المستخدمون',
  roles: 'الأدوار',
  categories: 'الفئات',
  brands: 'الماركات',
  units: 'الوحدات',
  suppliers: 'الموردون',
  clients: 'العملاء',
  employees: 'الموظفين',
  purchases: 'المشتريات',
  payments: 'الدفعات',
  shifts: 'الورديات',
  expenses: 'المصروفات',
}

export const FEATURE_LABELS: Record<string, { name: string; description: string }> = {
  multiple_units: { name: 'الوحدات المتعددة', description: 'دعم القطعة / الكرتونة / الكيلو للمنتج الواحد' },
  multiple_barcodes: { name: 'الباركود المتعدد', description: 'أكثر من باركود للمنتج أو الوحدة' },
  wholesale_price: { name: 'سعر الجملة', description: 'البيع بسعر الجملة في نقطة البيع' },
  product_discount: { name: 'خصم الصنف', description: 'تطبيق خصم على الأصناف داخل الفاتورة' },
  invoice_discount: { name: 'خصم الفاتورة', description: 'تطبيق خصم على إجمالي الفاتورة' },
  price_override: { name: 'تعديل السعر', description: 'التحكم في سعر الصنف أثناء البيع' },
  low_stock_report: { name: 'تقرير المخزون المنخفض', description: 'عرض المنتجات التي وصلت لحد إعادة الطلب' },
  receipt_printing: { name: 'طباعة الإيصالات', description: 'طباعة إيصالات البيع حراريًا' },
  barcode_printing: { name: 'طباعة الباركود', description: 'طباعة ملصقات الباركود' },
  categories: { name: 'الفئات', description: 'تصنيف المنتجات في فئات (بدون الفئات تظهر كأخرى)' },
  brands: { name: 'الماركات', description: 'ربط المنتجات بالماركة أو الشركة المصنعة' },
}
