export const PERMISSIONS = {
  PRODUCTS_VIEW: 'products.view',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_UPDATE: 'products.update',
  PRODUCTS_DELETE: 'products.delete',
  INVOICES_VIEW: 'invoices.view',
  INVOICES_CREATE: 'invoices.create',
  DISCOUNTS_PRODUCT: 'discounts.product',
  DISCOUNTS_INVOICE: 'discounts.invoice',
  PRICE_OVERRIDE: 'price.override',
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',
  PRINTING_RECEIPT: 'printing.receipt',
  PRINTING_BARCODE: 'printing.barcode',
  LICENSE_VIEW: 'license.view',
  LICENSE_MANAGE: 'license.manage',
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_UPDATE: 'settings.update',
  USERS_MANAGE: 'users.manage',
  ROLES_MANAGE: 'roles.manage',
} as const

export const FEATURES = {
  MULTIPLE_UNITS: 'multiple_units',
  MULTIPLE_BARCODES: 'multiple_barcodes',
  WHOLESALE_PRICE: 'wholesale_price',
  PRODUCT_DISCOUNT: 'product_discount',
  INVOICE_DISCOUNT: 'invoice_discount',
  PRICE_OVERRIDE: 'price_override',
  LOW_STOCK_REPORT: 'low_stock_report',
  RECEIPT_PRINTING: 'receipt_printing',
  BARCODE_PRINTING: 'barcode_printing',
} as const

export const PERMISSION_LABELS: Record<string, string> = {
  'products.view': 'عرض المنتجات',
  'products.create': 'إنشاء المنتجات',
  'products.update': 'تعديل المنتجات',
  'products.delete': 'حذف المنتجات',
  'invoices.view': 'عرض الفواتير',
  'invoices.create': 'إنشاء الفواتير',
  'discounts.product': 'خصم الصنف',
  'discounts.invoice': 'خصم الفاتورة',
  'price.override': 'تعديل السعر',
  'reports.view': 'عرض التقارير',
  'reports.export': 'تصدير التقارير',
  'printing.receipt': 'طباعة الإيصالات',
  'printing.barcode': 'طباعة الباركود',
  'license.view': 'عرض الترخيص',
  'license.manage': 'إدارة الترخيص',
  'settings.view': 'عرض الإعدادات',
  'settings.update': 'تعديل الإعدادات',
  'users.manage': 'إدارة المستخدمين',
  'roles.manage': 'إدارة الأدوار',
}

export const RESOURCE_LABELS: Record<string, string> = {
  products: 'المنتجات',
  invoices: 'الفواتير',
  discounts: 'الخصومات',
  price: 'الأسعار',
  reports: 'التقارير',
  printing: 'الطباعة',
  license: 'الترخيص',
  settings: 'الإعدادات',
  users: 'المستخدمون',
  roles: 'الأدوار',
}

export const FEATURE_LABELS: Record<string, { name: string; description: string }> = {
  multiple_units: { name: 'الوحدات المتعددة', description: 'دعم القطعة / الكرتونة / الكيلو للمنتج الواحد' },
  multiple_barcodes: { name: 'الباركود المتعدد', description: 'أكثر من باركود للمنتج أو الوحدة' },
  wholesale_price: { name: 'سعر الجملة', description: 'البيع بسعر الجملة في نقطة البيع' },
  product_discount: { name: 'خصم الصنف', description: 'تطبيق خصم على الأصناف داخل الفاتورة' },
  invoice_discount: { name: 'خصم الفاتورة', description: 'تطبيق خصم على إجمالي الفاتورة' },
  price_override: { name: 'تعديل السعر', description: 'التحكم في سعر الصنف أثناء البيع' },
  low_stock_report: { name: 'تقرير المخزون المنخفض', description: 'عرض المنتجات التي وصلت لحد إعادة الطلب' },
  receipt_printing: { name: 'طباعة الإيصالات', description: 'طباعة إيصالات البيع حراريًا' },
  barcode_printing: { name: 'طباعة الباركود', description: 'طباعة ملصقات الباركود' },
}
