ALTER TABLE "Product" ADD COLUMN "allowDiscount" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Product" ADD COLUMN "lowStockThreshold" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Invoice" ADD COLUMN "discountType" TEXT;
ALTER TABLE "Invoice" ADD COLUMN "discountValue" REAL NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN "discountAmount" REAL NOT NULL DEFAULT 0;

ALTER TABLE "InvoiceDetail" ADD COLUMN "discountAmount" REAL NOT NULL DEFAULT 0;
