INSERT OR IGNORE INTO "Permission" (id, key, name, description, resource, action, createdAt, updatedAt) VALUES
('products.view',       'products.view',       'View Products',       'View, search and list products',                              'products',  'view',     CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('products.create',     'products.create',     'Create Products',     'Create products (incl. POS unknown-barcode flow)',             'products',  'create',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('products.update',     'products.update',     'Update Products',     'Update products, units and barcodes',                          'products',  'update',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('products.delete',     'products.delete',     'Delete Products',     'Delete products',                                             'products',  'delete',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('invoices.view',       'invoices.view',       'View Invoices',       'View invoices and sales history',                              'invoices',  'view',     CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('invoices.create',     'invoices.create',     'Create Invoices',     'Ring up sales / create invoices',                              'invoices',  'create',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('discounts.product',   'discounts.product',   'Product Discount',    'Apply line/product-level discounts',                           'discounts', 'product',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('discounts.invoice',   'discounts.invoice',   'Invoice Discount',    'Apply invoice-level discounts',                                'discounts', 'invoice',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('price.override',      'price.override',      'Price Override',      'Override a line unit price during checkout',                  'price',     'override', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('reports.view',        'reports.view',        'View Reports',        'View reports (currently low-stock)',                           'reports',   'view',     CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('reports.export',      'reports.export',      'Export Reports',      'Export report data (proposed - no export UI yet)',             'reports',   'export',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('printing.receipt',    'printing.receipt',    'Print Receipts',      'Print thermal receipts',                                      'printing',  'receipt',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('printing.barcode',    'printing.barcode',    'Print Barcode Labels', 'Print barcode labels',                                       'printing',  'barcode',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('license.view',        'license.view',        'View License',        'Read license status (boot gate)',                              'license',   'view',     CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('license.manage',      'license.manage',      'Manage License',      'Unlock / manage license',                                     'license',   'manage',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('settings.view',       'settings.view',       'View Settings',       'View tenant settings / feature config',                        'settings',  'view',     CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('settings.update',     'settings.update',     'Update Settings',     'Change tenant settings / features',                            'settings',  'update',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('users.manage',        'users.manage',        'Manage Users',        'Manage users and their roles',                                 'users',     'manage',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('roles.manage',        'roles.manage',        'Manage Roles',        'Manage roles and role-permission assignments',                 'roles',     'manage',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
